# Default values for Quote of the Day system.

qotdbackend:
  image: "quay.io/rhdevelopers/qotd:db"
  dbpassword: "reallylongpassword99!"
  dbstorage: "8Gi"
  dbhost: "postgres"
  dbuser: "qotd"
  dbname: "quotesdb"
     
qotdwebsite:
  image: "quay.io/rhdevelopers/qotd-website-nodejs:latest"
# image: "quay.io/donschenck/qotd-frontend:openshiftfordotnetdevelopers"

frontend:
  replicas: 1

backend:
  replicas: 1
  qotd_api_url: SET_VALUE_HERE_OR_ENV_VAR

route:
  enabled: true

service:
  port: 8080
